services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgresql
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:

networks:
  postgresql:
    driver: bridge
